#' Read data from locally stored snapshots.
#'
#' Locally stored snapshots are generated by `fetch_data`.
#'
#' @export
#' @family extract
resume_data <- function() {
  occ_fn <- here::here("inst/data/occ.fst")

  stopifnot(fs::file_exists(occ_fn))

  list(
    occ = fst::read_fst(occ_fn)
  )
}

# usethis::use_test("resume_data")
